version: 2.1

jobs:
  scan-code-compare:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: current

      - run:
          name: Checkout baseline branch
          command: |
            git clone --single-branch --branch main ${CIRCLE_REPOSITORY_URL} main

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Pull Kodem CI image
          command: |
            docker pull us-docker.pkg.dev/kodem-public/kodem-ci/kodemci:v3.5.4

      - run:
          name: Run Kodem code scan with comparison
          command: |
            docker run --rm -t \
              -v "$(pwd)/current:/tmp/repo" \
              -v "$(pwd)/main:/tmp/baseline_repo" \
              -e KODEM_SERVICE_KEY="${KODEM_SERVICE_KEY}" \
              us-docker.pkg.dev/kodem-public/kodem-ci/kodemci:v3.5.4 \
              scan code-repository code /tmp/repo --output-severity=Critical,High --compare-with /tmp/baseline_repo

workflows:
  version: 2
  scan:
    jobs:
      - scan-code-compare